title: The Life of a Wolmers Boy
author: GitHub User
email: prudentchampion04@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will be about my life as a 8th grader at Wolmer's Boys School

# social links
github_username:  @legalremedy58

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
